### ISSUE TITLE
Camper Leaderboard API potentially calculating points incorrectly

### ISSUE THREAD

**Issue by zaclem01** [roelver/fcctop100#1]
#### Issue Description

When using the suggested API call in the Camper Leaderboard project, the total calculated points for the recent and alltime do not match the API calls for recent by total points and alltime by total points.
#### Steps To Reproduce

When calling `http://fcctop100.herokuapp.com/api/fccusers/top/recent` the results were as follows (example):

```
{"username":"wearenotgroot","img":"https://avatars.githubusercontent.com/u/16578279?v=3","alltime":632,"recent":368,"lastUpdate":"2016-02-28T08:09:15.011Z"}, ...
```

However, comparing it to the call for recent points by total using `http://fcctop100.herokuapp.com/api/fccusers/recent/total`, you get:

```
{"_id":"56ace0f7a733c603005869e5","username":"wearenotgroot","pointsRecent":389,"challengesRecent":7,"algorithmsRecent":9,"projectsRecent":5,"communityRecent":368,"totalRecent":639,"lastUpdate":"2016-02-28T08:09:15.011Z","img":"https://avatars.githubusercontent.com/u/16578279?v=3"},..
```

Notice that the `totalRecent` key is 389 in the latter call, whereas `recent` is 368 in the former. It looks like the `top/recent` is only pulling the community points and not the total.

In this example, the suggested `http://fcctop100.herokuapp.com/api/fccusers/top/recent` call yields the user wearenotgroot as the 2nd highest in recent points. But if we check that users recent ranking using `http://fcctop100.herokuapp.com/api/fccusers/ranking-r/wearenotgroot` it yields

```
{"_id":"56ace0f7a733c603005869e5","username":"wearenotgroot","existing":true,"points":942,"challenges":260,"algorithms":42,"projects":8,"community":632,"total":1342,"pointsRecent":389,"challengesRecent":7,"algorithmsRecent":9,"projectsRecent":5,"communityRecent":368,"totalRecent":639,"lastUpdate":"2016-02-28T08:09:15.011Z","__v":0,"img":"https://avatars.githubusercontent.com/u/16578279?v=3","following":[],"ranking":28}
```

This shows the actual rank as 28, which matches the users position when calling `http://fcctop100.herokuapp.com/api/fccusers/top/recent`.

Similar seeming errors occur when using the alltime calls.

I'm not sure if this is intentional, but I wanted to point it out in case it is a bug.
#### Browser Information
- Firefox, 44.0.2
- Windows 10
#### Screenshot

Suggested API call `http://fcctop100.herokuapp.com/api/fccusers/top/recent`
![Suggested API Call](https://i.gyazo.com/6b27521cdb27243563dfbbb64a6062ac.png)

Alternate API call `http://fcctop100.herokuapp.com/api/fccusers/recent/total`
![Alternate API call](https://i.gyazo.com/b15993f9083e43549d2906b181eafe14.png)

**Comment by roelver** [comment]
Your observations are correct, but also intended. 
The community score was introduced to encourage users to help each other in the chat. It is the number of points minus the number of points earned with challenges. 

The API for the FCC challenge (.../top/recent and .../top/alltime ) is a light version of the other API's, indeed only exposing the community scores, to keep the JSON response small. The only difference between both endpoints is in the ranking order.

The alternate API calls are not used, but since these values are pulled out of the same document in the database, I would not expect any differences.

I noticed that the community is sometimes a negative value (see user sajid-619) This looks weird, but that is caused by inconsistent counts on the FCC user page, if there are more completed challenges than points.

**Comment by zaclem01** [comment]
Understood, thanks for the response. I was just a little confused as I was using the individual user ranking call to make a preview pane for each user that broke down their scores in each area. When the scores didn't match, I wanted to make sure it was intended.

Closing the issue.
